In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [19]:
#อย่าลืมมมมมมมมมมมมมม รันตัวนี้ก่อนนนนนนน
import numpy as np

In [ ]:
#เรียกมา ลองกดปุ่ม dot+tab ดู
np.

In [14]:
#ลงชุดคำสั่งเพิ่ม
!pip install numpy

In [20]:
#เช็คเวอร์ชั่น สำคัญมาก เวลาใช้คำสั่งชาวบ้าน ตรวจดูว่าเวอร์ชั่นเหมือนของเรามั้ย
np.__version__

'1.19.5'

In [21]:
#ใช้ list ในการประกาศ
#เว็คเตอร์ หรือ array 1มิติ (1 dimensional array)
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
#array 2 มิติ or matrix array
a = np.array([[1,2,3],[4,5,6,],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#การแปลงข้อมูลให้อยู่ในรูปของ np.array ทำให้ทำอย่างอื่นได้โดยง่ายที่สุด

In [24]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[0]

1

In [86]:
a[2:5]

array([3, 4, 5])

In [87]:
# list ก็ทำได้เหมือนกัน
L = [1,2,3,4,5,6]
L[0]

1

In [88]:
L[2:5]

[3, 4, 5]

In [89]:
#เอาข้อมูลตั้งแต่ต้นจนถึงตำแหน่งที่6มา
a[:6]

array([1, 2, 3, 4, 5, 6])

In [90]:
L[:6]

[1, 2, 3, 4, 5, 6]

In [76]:
#ตั้งแต่ตำแหน่งที่3ขึ้นไปจนสุดมาโชว์
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [77]:
L[3:]

[]

In [ ]:
# -1 คือตำแหน่งสุดท้าย
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[-1]

In [78]:
a[-2]

9

In [ ]:
#ข้างหน้ามา2 ข้างหลังถอยมา3
a[2:-3]

In [79]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [80]:
a[-2:2]

array([], dtype=int64)

In [81]:
#เช็คขนาด array
np.size(a)

10

In [82]:
#แสดงถึงเว็คเตอร์
np.shape(a)

(10,)

In [83]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [84]:
#จาก a[a[2]] จะได้ a[3] จากนั้นจะได้ 4 (นับจาก 1 เป็นตำแหน่งที่ 0 )
a[a[2]]

4

In [91]:
#list ก็ทำได้เหมือนกัน
L[L[3]]

5

In [ ]:
L = [1,2,3,4,5,6]
L.reverse()
L

In [ ]:
#ทำไม่ได้เหมือน L
a.reverse()
a

In [ ]:
a = np.array([1,2,3,4,5,6,7])
np.shape(a)

In [93]:
#matrix ที่มี size ตั้งแต่ 1-7
a = a.reshape(1,7)
np.shape(a)

(1, 7)

In [ ]:
a

In [47]:
#matrix
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
#list ซ้อน list เฉยๆ
L = [[1,2,3],[4,5,6],[7,8,9]]
L

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [49]:
#แถวที่ 0 หลักที่ 0
a[0,0]

1

In [50]:
#list ทำแบบนี้ access ข้อมูลต่างกัน
L[0][0]

1

In [51]:
#แถวที่1 เอาข้อมูลทั้งหมดมาโชว์ แถวที่ 0 ค่ือ 1 2 3
a[1,:]

array([4, 5, 6])

In [52]:
L[1][:]

[4, 5, 6]

In [53]:
L[1]

[4, 5, 6]

In [54]:
a[1]

array([4, 5, 6])

In [55]:
#เอาคอลัมสุดท้ายทั้งหมดออกมาโชว์
a[:,-1]

array([3, 6, 9])

In [56]:
#ไม่เหมือน array ละ
L[:][-1]

[7, 8, 9]

In [94]:
#ดูคอลัมที่1ทั้งหมด จารย์จะเปลี่ยนให้เป็นเลข 0
a[:,1] = 0
a

array([[1, 0, 3, 4, 5, 6, 7]])

In [99]:
#set แถว ให้เป็น 0 ทั้งหมด
a[-1,:] = 0 
a

array([[0, 0, 0, 0, 0, 0, 0]])

In [98]:
#แถว 0 1 แต่ไม่ถึง2
a[0:2,:] = 8
a

array([[8, 8, 8, 8, 8, 8, 8]])

In [100]:
#matrix 3*3
a.shape

(1, 7)

In [101]:
#มีทั้งหมด9ตัว
a.size 

7

In [102]:
#มี่แถว
np.size(a,0)

1

In [103]:
#มี่กี่คอลลัม
np.size(a,1)

7

In [104]:
#ข้อมูลมีกี่ไดมนชั่น (มิติ)
a.ndim

2

In [105]:
#Data is Matrix
#rows = samples แนวยาว
#columns = attributes, features แนวตั้ง

np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [106]:
#ดึงข้อมูล ฟิค type ให้เป็นแบบไหน
np.array(np_mix_matrix[:,1], dtype=int)

array([2, 4, 6])

In [107]:
# 5 แถว 3 คอลัม ข้างในเป็น 0 หมด
a = np.zeros((5,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [108]:
a = np.ones((1,3))
a

array([[1., 1., 1.]])

In [109]:
a = np.ones((10))
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [110]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [69]:
#matrixที่เต็มไปด้วยเลข8
c = np.full((2,2),8)
c

array([[8, 8],
       [8, 8]])

In [164]:
a = np.ones((5,5))*8
a

array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]])

In [165]:
d = np.eye(5,5)
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [166]:
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

In [167]:
c*d

array([[8., 0.],
       [0., 8.]])

In [168]:
#เอาทั้ง
np.matmul(c,d)

array([[8., 8.],
       [8., 8.]])

In [169]:
np.sqrt(np.full((2,2),4))

array([[2., 2.],
       [2., 2.]])

In [170]:
a= np.ones((5,5))*9
a

array([[9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.]])

In [171]:
np.sqrt(a)

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [65]:
np.empty([5,5])

array([[1., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 1.],
       [1., 0., 0., 1., 1.],
       [1., 0., 0., 1., 0.]])

In [172]:
#ยกกำลัง
np.power(a,2)

array([[81., 81., 81., 81., 81.],
       [81., 81., 81., 81., 81.],
       [81., 81., 81., 81., 81.],
       [81., 81., 81., 81., 81.],
       [81., 81., 81., 81., 81.]])

In [173]:
def addone(a):
    return a + 1

In [33]:
#สั่ง random สุ่มตัวเลขตั้งแต่0-1 โดยมีอัตรการเกิดด้วยความน่าจะเป็นเท่่ากัน
np.random.rand()

0.4060469515362175

In [66]:
#สุ่มเลข 0-10
np.round(np.random.rand()*10)

3.0

In [38]:
#สุ่มมา 10 รอบ
[np.round(np.random.rand()*10) for item in range(10)]

[1.0, 3.0, 9.0, 5.0, 9.0, 4.0, 10.0, 1.0, 3.0, 9.0]

In [39]:
np.random.randint(5)

1

In [41]:
#ค่าที่ random ทุกครั้งจะเปลี่ยนหมด
[np.random.randint(5) for item in range(10)]

[0, 1, 3, 1, 2, 1, 4, 0, 3, 1]

In [42]:
[np.random.randint(5) for item in range(10)]

[2, 3, 4, 3, 2, 1, 4, 1, 3, 2]

In [43]:
#สุ่มเลข matrix ขนาด5*5
np.random.rand(5,5)


array([[0.91416578, 0.36253295, 0.02504776, 0.62847673, 0.31772177],
       [0.3324305 , 0.37591615, 0.41557379, 0.0984625 , 0.11830432],
       [0.3840898 , 0.89414388, 0.59321358, 0.90499036, 0.92797371],
       [0.65218145, 0.33686534, 0.18133288, 0.38724932, 0.13707276],
       [0.64923687, 0.56919923, 0.89570348, 0.62994867, 0.66515221]])

In [44]:
np.round(np.random.rand(5,5))

array([[0., 0., 1., 0., 1.],
       [0., 1., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.]])

In [68]:
#เลือกออกมา5อัน แต่มันซ้ำกันได้อยู่
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5)

array([10,  8,  6,  3,  6])

In [67]:
#สุ่มแบบไม่ซ้ำ
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5, replace=False)

array([ 7,  1,  4, 10,  8])

In [123]:
#สร้างเมทริกขนาด5*5
#ส้ร้างไอดีในการเลือกเมทริกนี้ 5 คือ 0 1 2 3 4 เลือกมา 3 ตัว โดยไม่ซ้ำ
np_matrix = np.round(np.random.rand(5,5))
idx_choose = np.random.choice(5,3, replace=False)
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

array([[1., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0.]])

In [124]:
#มีข้อมูลพันแถว แต่ละแถวมี5คอลัม
np_matrix = np.round(np.random.rand(1000,5))
np_matrix

array([[1., 1., 0., 1., 0.],
       [0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 1.],
       ...,
       [0., 1., 1., 1., 0.],
       [0., 0., 1., 0., 1.],
       [1., 1., 1., 0., 1.]])

In [125]:
#สุ่มเลือกมา 100 ตัว มีตัวเลขตั้งแต่0-999 เลือกมา100ตัว
idx_choose = np.random.choice(1000,100, replace=False)
idx_choose

array([501, 564, 540,  30, 862, 530, 964, 620, 547, 875, 610, 259, 408,
       277, 348, 864, 983, 733,  85, 871, 713, 851, 567, 314, 412, 873,
       927, 310, 150, 909, 174, 606, 275,  91, 404, 352, 267, 837, 634,
       668, 481, 327, 730, 137, 268, 158, 757,  11, 399, 792, 604, 582,
       488, 140, 138, 372,  69,  28, 680, 453,   3, 803, 769, 465, 414,
       234, 266, 523, 993,  77, 470,  21,   1, 665, 298,  24, 321, 822,
       600, 398, 405, 768, 270, 898, 307, 382,  90, 497, 556, 681,  43,
       427,  23, 652, 181, 629, 512, 860, 364, 830])

In [126]:
#เอาตัวเลขที่เราเลือก เข้าไปใช้เลือกแถว
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

array([[1., 0., 1., 1., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 1.],
       [1., 1., 0., 1., 0.],
       [0., 1., 0., 1., 1.],
       [1., 1., 1., 0., 0.],
       [1., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 1., 1.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1.],
       [0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [1., 1., 1., 1., 1.],
       [0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1.],
       [0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0.],
       [0., 1.

# Ex 2. 
Randomly create a matrix of size (10, 5) then randomly assign values of 0 and 1 to the last column of this matrix.**
#สุ่มสร้างเมริก10*5 แรนดอมให้ค่าระหว่าง0-1 จากนั้นเปลี่ยนคอลัมสุดท้ายให้เป็นเลข0กะ1เท่านั้น
#idx=index

In [129]:
np_matrix = np.random.rand(10,5)
np_matrix[:,4] = np.round(np_matrix[:,4])
np_matrix

array([[0.2784604 , 0.98099766, 0.31208198, 0.40853157, 0.        ],
       [0.08523043, 0.06101829, 0.26431885, 0.09506231, 0.        ],
       [0.81503242, 0.74852336, 0.70440185, 0.06255843, 1.        ],
       [0.32866568, 0.28846393, 0.15583403, 0.97658331, 1.        ],
       [0.37905361, 0.13020595, 0.70231884, 0.29408082, 0.        ],
       [0.35503682, 0.61155778, 0.20404939, 0.76307256, 1.        ],
       [0.30642021, 0.33253712, 0.0179936 , 0.78873011, 1.        ],
       [0.03398212, 0.97235965, 0.15569927, 0.16287317, 1.        ],
       [0.06476367, 0.53823362, 0.36586679, 0.15314258, 1.        ],
       [0.24025463, 0.95650875, 0.62664912, 0.06432308, 0.        ]])

In [174]:
np_matrix = np.round(np.random.rand(10,5))
idx_choose = np.random.choice(5,3, replace=False)
idx_choose

array([0, 2, 3])

In [131]:
np_matrix = np.random.randint(11,size = (5,5))
np_matrix

array([[8, 2, 1, 8, 8],
       [2, 4, 2, 4, 4],
       [0, 8, 2, 6, 3],
       [2, 8, 7, 0, 1],
       [8, 3, 5, 9, 2]])

In [176]:
#สุ่มmatrixมา
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[1, 1, 1, 2, 0],
       [0, 2, 0, 0, 0],
       [2, 2, 0, 2, 2],
       [1, 0, 0, 2, 2],
       [2, 1, 1, 1, 2]])

In [177]:
#ค้นหาข้อมูลใน matrix นี้ว่าตรงไหนเป็นเลข2บ้าง
#เก็บคู่ตำแหน่งเป็นลำดับ i j
i,j = np.where(np_matrix == 2)
[(i[ii],j[ii]) for ii in range(len(i))]

[(0, 3),
 (1, 1),
 (2, 0),
 (2, 1),
 (2, 3),
 (2, 4),
 (3, 3),
 (3, 4),
 (4, 0),
 (4, 4)]

In [139]:
row,column = np.where(np_matrix == 2)
[(row[i],column[i]) for i in range(len(row))]

[(0, 1),
 (0, 2),
 (1, 0),
 (1, 1),
 (1, 2),
 (2, 0),
 (2, 4),
 (3, 1),
 (3, 3),
 (3, 4)]

# Ex 3. 
Why we cannot use this index ? Please fix it !!**

In [146]:
idx = [1,2,3,4,5]
np_matrix[len(idx)-1,:]

array([0, 1, 0, 0, 0])

In [178]:
idx = [1,2,3,4,5]
idx

[1, 2, 3, 4, 5]

In [179]:
np_matrix = np.delete(np_matrix,[1,2],0)
np_matrix

array([[1, 1, 1, 2, 0],
       [1, 0, 0, 2, 2],
       [2, 1, 1, 1, 2]])

In [180]:
#แรนดอมแบบเก่า
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[0, 1, 1, 0, 0],
       [0, 1, 2, 2, 2],
       [0, 2, 0, 1, 0],
       [0, 1, 2, 1, 1],
       [1, 1, 0, 1, 1]])

In [181]:
#สร้าง randongeneration แล้ว set seed เป็น 0
rng = np.random.RandomState(0)
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[2, 2, 0, 1, 1],
       [2, 0, 2, 2, 0],
       [1, 2, 0, 2, 0],
       [2, 1, 2, 0, 0],
       [0, 0, 0, 1, 2]])

In [182]:
rng = np.random.RandomState(22)
np_matrix = rng.randint(3,size = (5,5))
np_matrix

array([[1, 0, 0, 0, 0],
       [2, 2, 0, 0, 0],
       [1, 2, 2, 0, 1],
       [0, 2, 1, 2, 1],
       [0, 0, 1, 0, 2]])

In [183]:
#rng ธรรมดา
rng = np.random.RandomState(0)
rng.rand()

0.5488135039273248

In [184]:
rng = np.random.RandomState(22)
np_matrix = rng.randint(3,size = (5,5))
np_matrix

array([[1, 0, 0, 0, 0],
       [2, 2, 0, 0, 0],
       [1, 2, 2, 0, 1],
       [0, 2, 1, 2, 1],
       [0, 0, 1, 0, 2]])

In [185]:
#เอาแถว 1 กะ 2 ออก
np_matrix = np.delete(np_matrix,[1,2],0)
np_matrix

array([[1, 0, 0, 0, 0],
       [0, 2, 1, 2, 1],
       [0, 0, 1, 0, 2]])

In [186]:
np_matrix = np.delete(np_matrix,[1,1],0)
np_matrix

array([[1, 0, 0, 0, 0],
       [0, 0, 1, 0, 2]])

In [187]:
#สร้าง matrix ที่เป็น T กับ F ให้
a = np_matrix == 2
a

array([[False, False, False, False, False],
       [False, False, False, False,  True]])

In [188]:
#เปลี่ยนทุกจุดในนี้ที่เป็นเลข 2 ให้เป็น 99

np_matrix[a] = 99
np_matrix

array([[ 1,  0,  0,  0,  0],
       [ 0,  0,  1,  0, 99]])

In [189]:
np_matrix [np_matrix == 2] =99
np_matrix

array([[ 1,  0,  0,  0,  0],
       [ 0,  0,  1,  0, 99]])

# **Ex 4.**

In [ ]:
# Ex 4. Randomly create a data matrix of 10 samples with 5 features. 
# Then, randomly create a label vector for 10 samples. 
# Finally, seperate samples into 2 groups
# Group 1 called train_data (label == 0)
# Group 2 called test_data (label == 1)
สร้างเมทริก สุ่มข้อมุล 10แถว5คอลัม
สร้างเวกเตอรที่ขนาดเท่ากับ10 1อัน
มีแค่ 0 1 เป็นหลัก
เปลี่ยนข้อมูล2กลุ่ม
กล่ม1 มีlebel=0 กลุ่ม2lebel=1 

In [147]:
#Randomly create a data matrix of 10 samples with 5 features.
matrix = np.random.randint(10,size = (10,5))
matrix

array([[5, 7, 2, 8, 0],
       [1, 8, 8, 1, 7],
       [3, 8, 6, 2, 8],
       [0, 9, 3, 2, 9],
       [9, 2, 1, 5, 1],
       [1, 7, 7, 3, 5],
       [8, 6, 4, 6, 2],
       [5, 2, 5, 2, 3],
       [8, 3, 7, 1, 9],
       [9, 0, 6, 1, 5]])

In [158]:
# Then, randomly create a label vector for 10 samples.
label_vector = np.random.randint(2,size = 10)
label_vector

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [162]:
# Finally, seperate samples into 2 groups
# Group 1 called train_data (label == 0)
# Group 2 called test_data (label == 1)

train_data = matrix[np.where(label_vector == 0)]
train_data

array([[3, 8, 6, 2, 8],
       [0, 9, 3, 2, 9],
       [8, 6, 4, 6, 2],
       [5, 2, 5, 2, 3],
       [8, 3, 7, 1, 9]])

In [163]:
test_data = matrix[np.where(label_vector == 1)]
test_data

array([[5, 7, 2, 8, 0],
       [1, 8, 8, 1, 7],
       [9, 2, 1, 5, 1],
       [1, 7, 7, 3, 5],
       [9, 0, 6, 1, 5]])